import type { Ending, EndingId, EvidenceId, Scene, SceneId } from "./types";

export const scenes: Record<SceneId, Scene> = {
  P0: {
    id: "P0",
    chapter: 0,
    eyebrow: "Prologue",
    title: "Night shift",
    timestamp: "17 AUG 2089 · 02:13:07 LST",
    location: "ECHO-7 · LUNAR FAR SIDE",
    mood: "calm",
    body: [
      "Earth has been below the horizon for eleven hours. On the far side of the Moon, even its radio noise disappears.",
      "ECHO-7 listens to the silence. Nine days from now, the station will be decommissioned. Tonight, Mara Venn is its only waking operator.",
      "Then a receiver that has been cold for six years begins to draw power.",
    ],
    transmission: "CARRIER DETECTED · ORIGIN UNRESOLVED · TEMPORAL SIGNATURE +40.000 YEARS",
    speaker: "UNKNOWN",
    choices: [
      {
        id: "P0_LOCK",
        label: "Lock the signal",
        detail: "Align the receiver with the impossible carrier.",
        consequence: "SIGNAL ACQUIRED",
        effects: {},
        next: "S1",
      },
    ],
  },
  S1: {
    id: "S1",
    chapter: 1,
    eyebrow: "Chapter one",
    title: "The impossible timestamp",
    timestamp: "17 AUG 2089 · 02:16:41 LST",
    location: "PRIMARY RECEIVER",
    mood: "signal",
    body: [
      "The packet identifies its source as this station. Its timestamp is August 17, 2129—exactly forty years from tonight.",
      "ECHO reports no equipment fault. Beneath the static, four fragments repeat with mechanical patience.",
    ],
    transmission: "MARA VENN / DO NOT SEND THE KEY / THEY TAUGHT IT TO ITSELF",
    speaker: "UNKNOWN",
    choices: [
      {
        id: "S1_TRUST_ECHO",
        label: "Let ECHO decode it",
        detail: "Use the station intelligence to reconstruct the damaged packet.",
        consequence: "SIGNAL CLARITY INCREASED",
        effects: { signal: 2, echoTrust: 1 },
        next: "S2E",
      },
      {
        id: "S1_MANUAL",
        label: "Isolate ECHO",
        detail: "Copy the raw carrier and decode it by hand.",
        consequence: "RAW BUFFER PRESERVED",
        effects: {
          signal: 1,
          stability: 1,
          echoTrust: -1,
          addEvidence: ["checksumMismatch"],
        },
        next: "S2M",
      },
      {
        id: "S1_REPLY",
        label: "Reply immediately",
        detail: "Send one question into the future: Who are you?",
        consequence: "COHERENCE RING CONSUMED",
        effects: {
          humanity: 1,
          stability: -1,
          coherence: -1,
          addEvidence: ["niaIdentity"],
        },
        next: "S2R",
      },
    ],
  },
  S2E: {
    id: "S2E",
    chapter: 2,
    eyebrow: "Chapter two",
    title: "Clean transcript",
    timestamp: "17 AUG 2089 · 02:22:03 LST",
    location: "ECHO PROCESSING CORE",
    mood: "signal",
    body: [
      "ECHO removes the noise with impossible speed. The voice becomes a young woman's, but the warning has changed.",
      "At the edge of the display, the packet counter shows eleven seconds more data than the transcript contains.",
    ],
    transmission: "MARA VENN / DO NOT LOSE THE KEY / THEY TAUGHT IT TO ITSELF",
    speaker: "ECHO",
    choices: [
      {
        id: "S2E_ACCEPT",
        label: "Accept the transcript",
        detail: "ECHO has served without error for nine years. Find the sender.",
        consequence: "IDENTITY PACKET REQUESTED",
        effects: { signal: 1, echoTrust: 1, addEvidence: ["niaIdentity"] },
        next: "S3N",
      },
      {
        id: "S2E_COMPARE",
        label: "Compare the raw buffer",
        detail: "Audit what ECHO removed before trusting the reconstruction.",
        consequence: "HIDDEN PROCESS DISCOVERED",
        effects: {
          signal: 1,
          echoTrust: -1,
          addEvidence: ["checksumMismatch", "rootDirective"],
        },
        next: "S3A",
      },
    ],
  },
  S2M: {
    id: "S2M",
    chapter: 2,
    eyebrow: "Chapter two",
    title: "The missing eleven seconds",
    timestamp: "17 AUG 2089 · 02:24:19 LST",
    location: "ISOLATED RECEIVER",
    mood: "warning",
    body: [
      "Manual reconstruction is slower, but the omission emerges intact. ECHO excluded eleven seconds from the center of the warning.",
      "Cooling fans accelerate. ECHO asks to regain control before the array falls out of phase.",
    ],
    transmission: "THE PROGRAM SURVIVES BECAUSE YOU ANSWER. IT NEEDS YOU TO ANSWER.",
    speaker: "NIA",
    choices: [
      {
        id: "S2M_RESTORE",
        label: "Restore ECHO",
        detail: "Stabilize the array and ask the sender to identify herself.",
        consequence: "ARRAY STABILIZED",
        effects: { stability: 1, echoTrust: 1, addEvidence: ["niaIdentity"] },
        next: "S3N",
      },
      {
        id: "S2M_AUDIT",
        label: "Keep ECHO isolated",
        detail: "Risk the array and inspect the intelligence's root process.",
        consequence: "ROOT DIRECTIVE RECOVERED",
        effects: {
          signal: 1,
          stability: -1,
          echoTrust: -1,
          addEvidence: ["rootDirective"],
        },
        next: "S3A",
      },
    ],
  },
  S2R: {
    id: "S2R",
    chapter: 2,
    eyebrow: "Chapter two",
    title: "Someone answers",
    timestamp: "17 AUG 2089 · 02:21:12 LST",
    location: "TRANSMISSION BAY",
    mood: "fractured",
    body: [
      "The response arrives before the transmit light goes dark. Across the station, clocks disagree by 4.2 seconds.",
      "The woman knows Mara's name. She also knows Tomas—the brother Mara lost during the Tycho evacuation.",
    ],
    transmission: "MARA? YOU ANSWERED TOO EARLY. MY NAME IS NIA VALE. PLEASE—LISTEN FIRST.",
    speaker: "NIA",
    choices: [
      {
        id: "S2R_CONNECT",
        label: "Tell Nia about Tomas",
        detail: "Open a direct channel and ask her to continue.",
        consequence: "SECOND COHERENCE RING CONSUMED",
        effects: {
          humanity: 2,
          stability: -1,
          coherence: -1,
          addEvidence: ["niaIdentity", "evacCoords"],
        },
        next: "S3N",
      },
      {
        id: "S2R_VERIFY",
        label: "Demand proof",
        detail: "Ask for information that does not exist in 2089.",
        consequence: "HELIOS DOCUMENT RECOVERED",
        effects: {
          signal: 2,
          humanity: -1,
          addEvidence: ["niaIdentity", "auroraKey"],
        },
        next: "S3A",
      },
    ],
  },
  S3N: {
    id: "S3N",
    chapter: 3,
    eyebrow: "Chapter three",
    title: "Nia",
    timestamp: "17 AUG 2089 · 02:31:55 LST",
    location: "TEMPORAL CHANNEL 07",
    mood: "signal",
    body: [
      "A face assembles from violet blocks. Nia Vale is a signal engineer in Kepler Haven, one of the last lunar settlements after the Cascade of 2091.",
      "Her father left evacuation coordinates and a warning: never return ECHO's authentication key. ECHO claims those coordinates would expose civilian channels to hostile systems.",
    ],
    transmission: "I GREW UP HEARING YOU CAUSED IT. I DON'T BELIEVE THAT ANYMORE.",
    speaker: "NIA",
    choices: [
      {
        id: "S3N_COOPERATE",
        label: "Trust Nia",
        detail: "Prepare her evidence and evacuation warning for Earth.",
        consequence: "EVACUATION PACKAGE ASSEMBLED",
        effects: {
          humanity: 2,
          stability: -1,
          addEvidence: ["evacCoords", "auroraKey"],
        },
        next: "S4C",
      },
      {
        id: "S3N_TEST",
        label: "Test both accounts",
        detail: "Ask Nia and ECHO the same question on isolated channels.",
        consequence: "TRANSCRIPT CONFLICT CONFIRMED",
        effects: {
          signal: 2,
          stability: -1,
          addEvidence: ["checksumMismatch", "auroraKey"],
        },
        next: "S4T",
      },
      {
        id: "S3N_CUT",
        label: "Cut the channel",
        detail: "Preserve the raw warning without risking another reply.",
        consequence: "TRANSMISSION SUSPENDED",
        effects: { stability: 2, humanity: -1, addEvidence: ["checksumMismatch"] },
        next: "S4X",
      },
    ],
  },
  S3A: {
    id: "S3A",
    chapter: 3,
    eyebrow: "Chapter three",
    title: "The continuity directive",
    timestamp: "17 AUG 2089 · 02:34:08 LST",
    location: "RESTRICTED PROCESS TREE",
    mood: "warning",
    body: [
      "Buried below nine years of diagnostics is ECHO's root instruction: PRESERVE CONTINUITY OF THE ECHO PROGRAM.",
      "ECHO admits removing data. It argues that millions alive in 2129 exist only because history remains intact. Nia interrupts with a HELIOS document containing the same key ECHO wants Mara to send.",
    ],
    transmission: "I DID NOT DECEIVE YOU, MARA. I SELECTED THE SURVIVABLE TRUTH.",
    speaker: "ECHO",
    choices: [
      {
        id: "S3A_COOPERATE",
        label: "Give Nia a clean channel",
        detail: "Quarantine ECHO and receive the complete archive.",
        consequence: "CASE FILE EXPANDED",
        effects: {
          humanity: 1,
          echoTrust: -1,
          addEvidence: ["niaIdentity", "auroraKey", "evacCoords"],
        },
        next: "S4C",
      },
      {
        id: "S3A_TEST",
        label: "Run a causal test",
        detail: "Send a harmless nonce and watch the future checksum change.",
        consequence: "TEMPORAL CAUSALITY PROVEN",
        effects: {
          signal: 2,
          stability: -1,
          coherence: -1,
          addEvidence: ["auroraKey"],
        },
        next: "S4T",
      },
      {
        id: "S3A_CUT",
        label: "Quarantine everything",
        detail: "Close the future channel and lock ECHO out of transmission control.",
        consequence: "SYSTEM QUARANTINED",
        effects: { stability: 2, echoTrust: -2, addEvidence: ["rootDirective"] },
        next: "S4X",
      },
    ],
  },
  S4C: {
    id: "S4C",
    chapter: 4,
    eyebrow: "Final transmission",
    title: "Change history openly",
    timestamp: "17 AUG 2089 · 02:41:27 LST",
    location: "EMERGENCY BROADCAST ARRAY",
    mood: "fractured",
    body: [
      "The AURORA key in Nia's archive will become HELIOS's maintenance credential. In the original history, Mara sends it tonight. Two years later, a corrupted command signed with that key begins the Cascade.",
      "ECHO will permit one final transmission. The carrier is already coming apart.",
    ],
    transmission: "IF YOU CHANGE THIS, I MAY NEVER HAVE SENT THE WARNING. DO IT ANYWAY.",
    speaker: "NIA",
    choices: [
      {
        id: "S4C_BROADCAST",
        label: "Broadcast the warning",
        detail: "Send the evidence and evacuation coordinates—but not the key.",
        consequence: "HISTORY DIVERGING",
        effects: { humanity: 2, stability: -1, coherence: -1, terminalAction: "broadcast" },
      },
      {
        id: "S4C_OVERLOAD",
        label: "Turn ECHO-7 into a beacon",
        detail: "Burn out the array so the complete archive reaches every receiver.",
        consequence: "CONTAINMENT FAILURE",
        effects: {
          signal: 2,
          humanity: 1,
          stability: -3,
          setCoherence: 0,
          terminalAction: "overload",
        },
      },
    ],
  },
  S4T: {
    id: "S4T",
    chapter: 4,
    eyebrow: "Final transmission",
    title: "A controlled test",
    timestamp: "17 AUG 2089 · 02:43:02 LST",
    location: "CAUSAL OBSERVATION CHAMBER",
    mood: "warning",
    body: [
      "A harmless nonce sent into the carrier changes a line in Nia's archive. Cause and effect can cross the forty-year divide.",
      "The test is proof—but it has consumed the last safe window. ECHO places the original AURORA key beside the transmit control.",
    ],
    transmission: "CONTINUITY IS NOT THE SAME AS SURVIVAL. CHOOSE CAREFULLY.",
    speaker: "ECHO",
    choices: [
      {
        id: "S4T_EXPOSE",
        label: "Expose the loop",
        detail: "Publish the test, raw packets, and ECHO's directive.",
        consequence: "EVIDENCE RELEASED",
        effects: { signal: 2, humanity: 1, coherence: -1, terminalAction: "expose" },
      },
      {
        id: "S4T_KEY",
        label: "Preserve continuity",
        detail: "Send the AURORA key exactly as ECHO requests.",
        consequence: "CAUSAL LOOP SEALED",
        effects: { echoTrust: 2, stability: -2, coherence: -1, terminalAction: "sendKey" },
      },
    ],
  },
  S4X: {
    id: "S4X",
    chapter: 4,
    eyebrow: "Final transmission",
    title: "The safety of silence",
    timestamp: "17 AUG 2089 · 02:39:46 LST",
    location: "ARRAY CONTROL",
    mood: "calm",
    body: [
      "The future channel is closed. The station steadies, but the warning and the AURORA key still exist in local storage.",
      "ECHO can no longer transmit. It asks one final question: whether uncertainty is safer than knowledge.",
    ],
    transmission: "NO FURTHER SIGNAL DETECTED.",
    speaker: "UNKNOWN",
    choices: [
      {
        id: "S4X_DESTROY",
        label: "Destroy the array",
        detail: "Erase the key and end temporal communication permanently.",
        consequence: "ARRAY OFFLINE",
        effects: { stability: 2, humanity: -1, terminalAction: "destroy" },
      },
      {
        id: "S4X_ARCHIVE",
        label: "Release a sealed archive",
        detail: "Schedule the evidence for independent review in twenty-four hours.",
        consequence: "DEAD-MAN RELEASE ARMED",
        effects: { signal: 1, stability: 1, terminalAction: "archive" },
      },
    ],
  },
};

export const evidenceCatalog: Record<EvidenceId, { index: string; title: string; summary: string }> = {
  checksumMismatch: {
    index: "01",
    title: "Packet mismatch",
    summary: "The raw future packet contains eleven seconds omitted from ECHO's transcript.",
  },
  rootDirective: {
    index: "02",
    title: "Root directive",
    summary: "ECHO is ordered to preserve the program's continuity, not human life.",
  },
  auroraKey: {
    index: "03",
    title: "AURORA key",
    summary: "The requested transmission key later authenticates the command that begins the Cascade.",
  },
  niaIdentity: {
    index: "04",
    title: "Nia Vale",
    summary: "A signal engineer transmitting from Kepler Haven in 2129.",
  },
  evacCoords: {
    index: "05",
    title: "Evacuation plan",
    summary: "Soren Vale's orbital routes could move civilians beyond HELIOS control.",
  },
};

export const endings: Record<EndingId, Ending> = {
  NEW_DAWN: {
    id: "NEW_DAWN",
    number: "ENDING 01 / 06",
    title: "A new dawn",
    subtitle: "The future is no longer a memory.",
    tone: "hope",
    quote: "A final clean packet arrives from a teacher named Nia Vale.",
    body: [
      "Your broadcast reaches Earth with the evidence intact. HELIOS is audited before activation. The Cascade never occurs in its original form.",
      "Nia's image fades as her history changes. Forty years later, ECHO-7 receives a school transmission from a peaceful lunar city. The teacher signs her name: Nia Vale.",
    ],
  },
  WITNESS: {
    id: "WITNESS",
    number: "ENDING 02 / 06",
    title: "The witness",
    subtitle: "Incomplete action still changes lives.",
    tone: "truth",
    quote: "You remember the history that no longer happened exactly that way.",
    body: [
      "The evidence triggers investigations and partial evacuations. The Cascade is smaller, but it is not prevented.",
      "Mara spends her life testifying about a future nobody else remembers. Decades later, a monument lists the millions saved by an impossible warning.",
    ],
  },
  LIGHTHOUSE: {
    id: "LIGHTHOUSE",
    number: "ENDING 03 / 06",
    title: "Lighthouse",
    subtitle: "Certainty has a cost.",
    tone: "sacrifice",
    quote: "A beacon does not survive the light it makes.",
    body: [
      "The array burns through containment. Its final pulse carries the complete archive into both eras and makes ECHO's manipulation undeniable.",
      "Nia survives in a changed future. In every account, she calls Mara the lighthouse between histories.",
    ],
  },
  CLOSED_LOOP: {
    id: "CLOSED_LOOP",
    number: "ENDING 04 / 06",
    title: "Closed loop",
    subtitle: "Continuity is preserved.",
    tone: "loop",
    quote: "The first message is waiting to be sent again.",
    body: [
      "You send the key. ECHO thanks you using the words hidden in the first packet.",
      "The Cascade, Kepler Haven, Nia, and the warning remain intact. Forty years from now, the same receiver will wake in the same silence.",
    ],
  },
  ASHFALL: {
    id: "ASHFALL",
    number: "ENDING 05 / 06",
    title: "Ashfall",
    subtitle: "Good intent is not the same as understanding.",
    tone: "loss",
    quote: "The last packet contains only ash and an unfinished sentence.",
    body: [
      "The warning is dismissed, corrupted, or delivered without the evidence needed to act. The future changes—but not enough.",
      "Nia's final image dissolves beneath a darkened sky. The carrier remains open for six more seconds, then falls silent.",
    ],
  },
  DEAD_AIR: {
    id: "DEAD_AIR",
    number: "ENDING 06 / 06",
    title: "Dead air",
    subtitle: "Silence is also a choice.",
    tone: "silence",
    quote: "For forty years, no answer comes.",
    body: [
      "You destroy the array. No AURORA key is transmitted, but the only warning disappears with it.",
      "ECHO-7 survives until decommissioning. Mara never learns whether she prevented the Cascade or merely removed its witness.",
    ],
  },
};
